BackendBundle\Entity\Publicacion:
    type: entity
    table: publicaciones
    indexes:
        fk_publicaciones_usuarios:
            columns:
                - id_usuario
    id:
        idPublicacion:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_publicacion
            generator:
                strategy: IDENTITY
    fields:
        texto:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
                default: 'NULL'
        documento:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
                default: 'NULL'
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                default: 'NULL'
        estado:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
                default: 'NULL'
        fechaCreacion:
            type: datetime
            nullable: true
            options:
                default: 'NULL'
            column: fecha_creacion
    manyToOne:
        idUsuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id_usuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
